sudo: false
language: php
php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - hhvm
install:
  - if [ -n "$GITHUB_OAUTH_TOKEN" ]; then composer config github-oauth.github.com ${GITHUB_OAUTH_TOKEN}; fi;
  - composer install
script:
  - if [[ ${TRAVIS_PHP_VERSION} != "hhvm" ]]; then vendor/bin/codecept run -v --steps  --coverage --coverage-xml --coverage-html; fi
cache:
  directories:
    - $HOME/.composer/cache